name: sentryConfig

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'The commit hash (or branch/tag) to build'
        required: true
        default: 'master'

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commit_hash }}

      - name: Install dependencies
        env:
          SENTRY_RELEASE: inventory-${{ github.event.inputs.commit_hash }}
        run: npm ci

      - name: Build
        env:
          SENTRY_RELEASE: inventory-${{ github.event.inputs.commit_hash }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        run: npm run build --if-present

